version: '3'

services:
    messatsuu:
        container_name: messatsuu-home
        image: nicolasfhirsig/namp:v1
        # security_opt:
        # - seccomp:unconfined
        ports: 
            - "8000:80"
            - "3600:3306"
        volumes:
            - ./:/var/www/html/
